function appendCaptureLog(logCsv, result, cfg)
%APPENDCAPTURELOG Append one capture result to CSV log.

    row = table( ...
        string(result.timestamp), ...
        result.sample_id, ...
        result.slide_index, ...
        string(result.content_id), ...
        string(result.content_type), ...
        string(result.font_name), ...
        result.font_size_pt, ...
        string(result.theme), ...
        string(result.notes), ...
        string(result.ppt_filename), ...
        string(result.filename), ...
        cfg.sdr.fc, ...
        cfg.sdr.fs, ...
        cfg.sdr.capture_time_s, ...
        cfg.sdr.samplesPerFrame, ...
        result.received_samples, ...
        result.theoretical_samples, ...
        result.sample_margin, ...
        result.warmup_overrun, ...
        result.total_overrun, ...
        result.elapsed_s, ...
        result.ok, ...
        'VariableNames', { ...
            'timestamp', 'sample_id', 'slide_index', 'content_id', ...
            'content_type', 'font_name', 'font_size_pt', 'theme', 'notes', ...
            'ppt_filename', 'capture_filename', 'fc_hz', 'fs_hz', ...
            'capture_time_s', 'samples_per_frame', 'received_samples', ...
            'theoretical_samples', 'sample_margin', 'warmup_overrun', ...
            'total_overrun', 'elapsed_s', 'ok'} ...
    );

    if exist(logCsv, 'file')
        old = readtable(logCsv);
        allRows = [old; row];
    else
        allRows = row;
    end

    writetable(allRows, logCsv);
end