function rx = x310CreateRx(cfg)
%X310CREATERX Create and return a reusable X310 receiver object.

    sdr = cfg.sdr;

    rx = comm.SDRuReceiver( ...
        'Platform', 'X310', ...
        'IPAddress', sdr.ip_addr, ...
        'CenterFrequency', sdr.fc, ...
        'MasterClockRate', sdr.masterClockRate, ...
        'DecimationFactor', sdr.decimationFactor, ...
        'Gain', sdr.gain_dB, ...
        'SamplesPerFrame', sdr.samplesPerFrame, ...
        'OutputDataType', sdr.outputDataType);
end